version: '3'

services:

    # zigbee to mqtt bridge
    zigbee2mqtt:
        build: zigbee/zigbee2mqtt
        restart: unless-stopped
        volumes:
            - ./data/zigbee2mqtt:/app/data
            - ./zigbee/zigbee2mqtt/configuration.yaml.template:/configuration.yaml.template:ro
            - /run/udev:/run/udev:ro
        devices:
            - /dev/ttyACM0:/dev/ttyACM0
        privileged: true
        env_file:
            - config
        logging:
            driver: "${LOGGING_DRIVER}"
        ports:
            - 8880:8080

    zigbee2loxone_bridge:                
        build: zigbee/zigbee2loxone_bridge/bridge
        restart: unless-stopped
        volumes:
            - ./data:/data
            - groovy_grapes:/home/groovy/.groovy/grapes
        env_file:
            - config
        environment:
            - BRIDGE_CONFIG_FILE=/data/zigbee2loxone.json
        logging:
            driver: "${LOGGING_DRIVER}"


    #zigbee2mqttAssistant:
        #image: carldebilly/zigbee2mqttassistant
        #container_name: zigbee2mqttAssistant
        #restart: unless-stopped
        #env_file:
            #- config
        #ports:
            #- 8882:80

            
volumes:
    # gradle grape cache
    groovy_grapes:
