version: '2'

services:

  influxdb:
      image: influxdb:1.0
      restart: always
      ports:
        - "8083:8083"
        - "8086:8086"
        - "25826:25826/udp"
      volumes:
        - ${INFLUXDB_DIR}:/var/lib/influxdb
        - ./influxdb.conf:/etc/influxdb/influxdb.conf

  grafana:
      image: grafana/grafana:4.2.0
      restart: always
      ports:
        - "3000:3000"
      volumes:
        - ${GRAFANA_DIR}:/var/lib/grafana

#  loxone2influx:
#    build: loxone2influx
#    restart: always
