version: '3'

services:

    # zigbee to mqtt bridge
    zigbee2mqtt:
        build: zigbee2mqtt
        network_mode: host
        restart: always
        volumes:
            - ./zigbee2mqtt/data:/app/data
            - ./zigbee2mqtt/configuration.yaml.template:/configuration.yaml.template:ro
            - /run/udev:/run/udev:ro
        devices:
            - /dev/ttyACM0:/dev/ttyACM0
        privileged: true
        env_file:
            - ./config
        logging:
            driver: "${LOGGING_DRIVER}"

    # zigbee2mqtt manager
    zigbee2mqtt_manager:
        build: zigbee2mqtt_manager
        network_mode: host
        restart: always
        volumes:
            - ./settings.json:/settings.json
        env_file:
            - ./config
        environment:
          SERVER_PORT: 8881
          SETTINGS_JSON: /settings.json
        logging:
            driver: "${LOGGING_DRIVER}"
